#!/usr/bin/env bash
# package update and install nginx
sudo apt-get update
sudo apt-get install -y nginx

#allow nginx on firewall
sudo ufw allow 'Nginx HTTp'

#configure nginx
echo 'Hello World!' > /var/www/html/index.html

#restart nginx
sudo service nginx restart

