#!/usr/bin/env bash
#display with changes in 4th and 8th loop
declare -i idx=0
while ((idx<10))
do
	if ((idx == 3))
	then
		echo "bad luck"
	elif ((idx == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((idx++))
done
